name: COUNTER VIDEO PRIVATE UPDATE

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '30 6 * * *'   # 12:00 PM IST
  #   - cron: '30 8 * * *'   # 2:00 PM IST

jobs:
  run-script:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            TELEGRAM/telegram_video_private/counter_video_private.py
            TELEGRAM/telegram_video_private/counter_video_private.txt
          fetch-depth: 1

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.9'  # Specify the Python version you need

      # Install the necessary packages
      - name: Installed package list
        run: apt list --installed

      # Run your Python script
      - name: Run Python script
        run: |
          cd TELEGRAM/telegram_video_private
          python3 counter_video_private.py

      # Check if TELEGRAM/telegram_video_private/counter_video_private.txt has been modified, pull, and push the modified changes.
      - name: Commit and Push Changes
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git add TELEGRAM/telegram_video_private/counter_video_private.txt
          git commit -m "Update TELEGRAM/telegram_video_private/counter_video_private.txt after processing" || echo "No changes to commit"
          git pull --rebase origin main || echo "No changes to pull"
          git push || echo "No changes to push"
