name: TELEGRAM PRIVATE VIDEO UPLOADER

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '30 7 * * *'   # Runs at 1:00 PM IST
  
jobs:
  run-script:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.9'  # Specify the Python version you need
      
      # Install the necessary packages
      - name: Installed package list
        run: apt list --installed

      # Install dependencies
      - name: Install dependencies
        run: |
         python3 -m pip install --upgrade pip
         pip3 install -r requirements.txt

      # Run your Python script
      - name: Run Python script
        env:
          NAIRAGRAM_PRIVATE_BOT_TOKEN: ${{ secrets.NAIRAGRAM_PRIVATE_BOT_TOKEN }}
          NAIRAGRAM_PRIVATE_CHAT_ID: ${{ secrets.NAIRAGRAM_PRIVATE_CHAT_ID }}
          RENDER_BASE_VIDEO_URL: ${{ secrets.RENDER_BASE_VIDEO_URL }}
        run: python3 TELEGRAM/telegram_video_private/telegram_video_private.py
